/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LCodeRouteImport } from './routes/l/$code'
import { Route as DashboardWalletIndexRouteImport } from './routes/dashboard/wallet/index'
import { Route as DashboardVoucherGeneratorIndexRouteImport } from './routes/dashboard/voucher-generator/index'
import { Route as DashboardTransactionIndexRouteImport } from './routes/dashboard/transaction/index'
import { Route as DashboardSettingIndexRouteImport } from './routes/dashboard/setting/index'
import { Route as DashboardProductIndexRouteImport } from './routes/dashboard/product/index'
import { Route as DashboardPlatformProductIndexRouteImport } from './routes/dashboard/platform-product/index'
import { Route as DashboardManualBookIndexRouteImport } from './routes/dashboard/manual-book/index'
import { Route as DashboardEmailIndexRouteImport } from './routes/dashboard/email/index'
import { Route as DashboardEmailMessageIndexRouteImport } from './routes/dashboard/email-message/index'
import { Route as DashboardAccountsettingIndexRouteImport } from './routes/dashboard/accountsetting/index'
import { Route as DashboardAccountIndexRouteImport } from './routes/dashboard/account/index'
import { Route as DashboardTransactionCreateRouteImport } from './routes/dashboard/transaction/create'
import { Route as DashboardProductCreateRouteImport } from './routes/dashboard/product/create'
import { Route as DashboardPlatformProductCreateRouteImport } from './routes/dashboard/platform-product/create'
import { Route as DashboardPlatformProductIdRouteImport } from './routes/dashboard/platform-product/$id'
import { Route as DashboardManualBookWriteRouteImport } from './routes/dashboard/manual-book/write'
import { Route as DashboardManualBookSlugRouteImport } from './routes/dashboard/manual-book/$slug'
import { Route as DashboardEmailCreateRouteImport } from './routes/dashboard/email/create'
import { Route as DashboardEmailIdRouteImport } from './routes/dashboard/email/$id'
import { Route as DashboardAccountsettingDevicesRouteImport } from './routes/dashboard/accountsetting/devices'
import { Route as DashboardAccountCreateRouteImport } from './routes/dashboard/account/create'
import { Route as DashboardAccountSlugRouteImport } from './routes/dashboard/account/$slug'
import { Route as DashboardAttendanceMeRouteRouteImport } from './routes/dashboard/attendance/me/route'
import { Route as DashboardAccountsettingShiftRouteRouteImport } from './routes/dashboard/accountsetting/shift/route'
import { Route as DashboardWalletBankAccountIndexRouteImport } from './routes/dashboard/wallet/bank-account/index'
import { Route as DashboardSettingTutorialIndexRouteImport } from './routes/dashboard/setting/tutorial.index'
import { Route as DashboardSettingLandingIndexRouteImport } from './routes/dashboard/setting/landing.index'
import { Route as DashboardSettingArticleIndexRouteImport } from './routes/dashboard/setting/article.index'
import { Route as DashboardAccountsettingWithdrawalIndexRouteImport } from './routes/dashboard/accountsetting/withdrawal/index'
import { Route as DashboardAccountsettingStaffIndexRouteImport } from './routes/dashboard/accountsetting/staff/index'
import { Route as DashboardAccountsettingRoleIndexRouteImport } from './routes/dashboard/accountsetting/role/index'
import { Route as DashboardAccountsettingAttendanceIndexRouteImport } from './routes/dashboard/accountsetting/attendance/index'
import { Route as DashboardManualBookEditIdRouteImport } from './routes/dashboard/manual-book/edit.$id'
import { Route as DashboardAccountsettingStaffCreateRouteImport } from './routes/dashboard/accountsetting/staff/create'
import { Route as DashboardAccountsettingRoleCreateRouteImport } from './routes/dashboard/accountsetting/role/create'
import { Route as DashboardAccountsettingRoleRoleIdRouteImport } from './routes/dashboard/accountsetting/role/$roleId'
import { Route as DashboardAccountsettingAttendanceReportRouteRouteImport } from './routes/dashboard/accountsetting/attendance/report/route'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const LCodeRoute = LCodeRouteImport.update({
  id: '/l/$code',
  path: '/l/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletIndexRoute = DashboardWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardVoucherGeneratorIndexRoute =
  DashboardVoucherGeneratorIndexRouteImport.update({
    id: '/voucher-generator/',
    path: '/voucher-generator/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTransactionIndexRoute =
  DashboardTransactionIndexRouteImport.update({
    id: '/transaction/',
    path: '/transaction/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingIndexRoute = DashboardSettingIndexRouteImport.update({
  id: '/setting/',
  path: '/setting/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductIndexRoute = DashboardProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlatformProductIndexRoute =
  DashboardPlatformProductIndexRouteImport.update({
    id: '/platform-product/',
    path: '/platform-product/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardManualBookIndexRoute =
  DashboardManualBookIndexRouteImport.update({
    id: '/manual-book/',
    path: '/manual-book/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmailIndexRoute = DashboardEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmailMessageIndexRoute =
  DashboardEmailMessageIndexRouteImport.update({
    id: '/email-message/',
    path: '/email-message/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsettingIndexRoute =
  DashboardAccountsettingIndexRouteImport.update({
    id: '/accountsetting/',
    path: '/accountsetting/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountIndexRoute = DashboardAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTransactionCreateRoute =
  DashboardTransactionCreateRouteImport.update({
    id: '/transaction/create',
    path: '/transaction/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductCreateRoute = DashboardProductCreateRouteImport.update({
  id: '/product/create',
  path: '/product/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlatformProductCreateRoute =
  DashboardPlatformProductCreateRouteImport.update({
    id: '/platform-product/create',
    path: '/platform-product/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPlatformProductIdRoute =
  DashboardPlatformProductIdRouteImport.update({
    id: '/platform-product/$id',
    path: '/platform-product/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardManualBookWriteRoute =
  DashboardManualBookWriteRouteImport.update({
    id: '/manual-book/write',
    path: '/manual-book/write',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardManualBookSlugRoute = DashboardManualBookSlugRouteImport.update({
  id: '/manual-book/$slug',
  path: '/manual-book/$slug',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmailCreateRoute = DashboardEmailCreateRouteImport.update({
  id: '/email/create',
  path: '/email/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmailIdRoute = DashboardEmailIdRouteImport.update({
  id: '/email/$id',
  path: '/email/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountsettingDevicesRoute =
  DashboardAccountsettingDevicesRouteImport.update({
    id: '/accountsetting/devices',
    path: '/accountsetting/devices',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountCreateRoute = DashboardAccountCreateRouteImport.update({
  id: '/account/create',
  path: '/account/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountSlugRoute = DashboardAccountSlugRouteImport.update({
  id: '/account/$slug',
  path: '/account/$slug',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAttendanceMeRouteRoute =
  DashboardAttendanceMeRouteRouteImport.update({
    id: '/attendance/me',
    path: '/attendance/me',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsettingShiftRouteRoute =
  DashboardAccountsettingShiftRouteRouteImport.update({
    id: '/accountsetting/shift',
    path: '/accountsetting/shift',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardWalletBankAccountIndexRoute =
  DashboardWalletBankAccountIndexRouteImport.update({
    id: '/wallet/bank-account/',
    path: '/wallet/bank-account/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingTutorialIndexRoute =
  DashboardSettingTutorialIndexRouteImport.update({
    id: '/setting/tutorial/',
    path: '/setting/tutorial/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingLandingIndexRoute =
  DashboardSettingLandingIndexRouteImport.update({
    id: '/setting/landing/',
    path: '/setting/landing/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingArticleIndexRoute =
  DashboardSettingArticleIndexRouteImport.update({
    id: '/setting/article/',
    path: '/setting/article/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsettingWithdrawalIndexRoute =
  DashboardAccountsettingWithdrawalIndexRouteImport.update({
    id: '/accountsetting/withdrawal/',
    path: '/accountsetting/withdrawal/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsettingStaffIndexRoute =
  DashboardAccountsettingStaffIndexRouteImport.update({
    id: '/accountsetting/staff/',
    path: '/accountsetting/staff/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsettingRoleIndexRoute =
  DashboardAccountsettingRoleIndexRouteImport.update({
    id: '/accountsetting/role/',
    path: '/accountsetting/role/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsettingAttendanceIndexRoute =
  DashboardAccountsettingAttendanceIndexRouteImport.update({
    id: '/accountsetting/attendance/',
    path: '/accountsetting/attendance/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardManualBookEditIdRoute =
  DashboardManualBookEditIdRouteImport.update({
    id: '/manual-book/edit/$id',
    path: '/manual-book/edit/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsettingStaffCreateRoute =
  DashboardAccountsettingStaffCreateRouteImport.update({
    id: '/accountsetting/staff/create',
    path: '/accountsetting/staff/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsettingRoleCreateRoute =
  DashboardAccountsettingRoleCreateRouteImport.update({
    id: '/accountsetting/role/create',
    path: '/accountsetting/role/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsettingRoleRoleIdRoute =
  DashboardAccountsettingRoleRoleIdRouteImport.update({
    id: '/accountsetting/role/$roleId',
    path: '/accountsetting/role/$roleId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsettingAttendanceReportRouteRoute =
  DashboardAccountsettingAttendanceReportRouteRouteImport.update({
    id: '/accountsetting/attendance/report',
    path: '/accountsetting/attendance/report',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/billing': typeof BillingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/l/$code': typeof LCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/accountsetting/shift': typeof DashboardAccountsettingShiftRouteRoute
  '/dashboard/attendance/me': typeof DashboardAttendanceMeRouteRoute
  '/dashboard/account/$slug': typeof DashboardAccountSlugRoute
  '/dashboard/account/create': typeof DashboardAccountCreateRoute
  '/dashboard/accountsetting/devices': typeof DashboardAccountsettingDevicesRoute
  '/dashboard/email/$id': typeof DashboardEmailIdRoute
  '/dashboard/email/create': typeof DashboardEmailCreateRoute
  '/dashboard/manual-book/$slug': typeof DashboardManualBookSlugRoute
  '/dashboard/manual-book/write': typeof DashboardManualBookWriteRoute
  '/dashboard/platform-product/$id': typeof DashboardPlatformProductIdRoute
  '/dashboard/platform-product/create': typeof DashboardPlatformProductCreateRoute
  '/dashboard/product/create': typeof DashboardProductCreateRoute
  '/dashboard/transaction/create': typeof DashboardTransactionCreateRoute
  '/dashboard/account': typeof DashboardAccountIndexRoute
  '/dashboard/accountsetting': typeof DashboardAccountsettingIndexRoute
  '/dashboard/email-message': typeof DashboardEmailMessageIndexRoute
  '/dashboard/email': typeof DashboardEmailIndexRoute
  '/dashboard/manual-book': typeof DashboardManualBookIndexRoute
  '/dashboard/platform-product': typeof DashboardPlatformProductIndexRoute
  '/dashboard/product': typeof DashboardProductIndexRoute
  '/dashboard/setting': typeof DashboardSettingIndexRoute
  '/dashboard/transaction': typeof DashboardTransactionIndexRoute
  '/dashboard/voucher-generator': typeof DashboardVoucherGeneratorIndexRoute
  '/dashboard/wallet': typeof DashboardWalletIndexRoute
  '/dashboard/accountsetting/attendance/report': typeof DashboardAccountsettingAttendanceReportRouteRoute
  '/dashboard/accountsetting/role/$roleId': typeof DashboardAccountsettingRoleRoleIdRoute
  '/dashboard/accountsetting/role/create': typeof DashboardAccountsettingRoleCreateRoute
  '/dashboard/accountsetting/staff/create': typeof DashboardAccountsettingStaffCreateRoute
  '/dashboard/manual-book/edit/$id': typeof DashboardManualBookEditIdRoute
  '/dashboard/accountsetting/attendance': typeof DashboardAccountsettingAttendanceIndexRoute
  '/dashboard/accountsetting/role': typeof DashboardAccountsettingRoleIndexRoute
  '/dashboard/accountsetting/staff': typeof DashboardAccountsettingStaffIndexRoute
  '/dashboard/accountsetting/withdrawal': typeof DashboardAccountsettingWithdrawalIndexRoute
  '/dashboard/setting/article': typeof DashboardSettingArticleIndexRoute
  '/dashboard/setting/landing': typeof DashboardSettingLandingIndexRoute
  '/dashboard/setting/tutorial': typeof DashboardSettingTutorialIndexRoute
  '/dashboard/wallet/bank-account': typeof DashboardWalletBankAccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/l/$code': typeof LCodeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/accountsetting/shift': typeof DashboardAccountsettingShiftRouteRoute
  '/dashboard/attendance/me': typeof DashboardAttendanceMeRouteRoute
  '/dashboard/account/$slug': typeof DashboardAccountSlugRoute
  '/dashboard/account/create': typeof DashboardAccountCreateRoute
  '/dashboard/accountsetting/devices': typeof DashboardAccountsettingDevicesRoute
  '/dashboard/email/$id': typeof DashboardEmailIdRoute
  '/dashboard/email/create': typeof DashboardEmailCreateRoute
  '/dashboard/manual-book/$slug': typeof DashboardManualBookSlugRoute
  '/dashboard/manual-book/write': typeof DashboardManualBookWriteRoute
  '/dashboard/platform-product/$id': typeof DashboardPlatformProductIdRoute
  '/dashboard/platform-product/create': typeof DashboardPlatformProductCreateRoute
  '/dashboard/product/create': typeof DashboardProductCreateRoute
  '/dashboard/transaction/create': typeof DashboardTransactionCreateRoute
  '/dashboard/account': typeof DashboardAccountIndexRoute
  '/dashboard/accountsetting': typeof DashboardAccountsettingIndexRoute
  '/dashboard/email-message': typeof DashboardEmailMessageIndexRoute
  '/dashboard/email': typeof DashboardEmailIndexRoute
  '/dashboard/manual-book': typeof DashboardManualBookIndexRoute
  '/dashboard/platform-product': typeof DashboardPlatformProductIndexRoute
  '/dashboard/product': typeof DashboardProductIndexRoute
  '/dashboard/setting': typeof DashboardSettingIndexRoute
  '/dashboard/transaction': typeof DashboardTransactionIndexRoute
  '/dashboard/voucher-generator': typeof DashboardVoucherGeneratorIndexRoute
  '/dashboard/wallet': typeof DashboardWalletIndexRoute
  '/dashboard/accountsetting/attendance/report': typeof DashboardAccountsettingAttendanceReportRouteRoute
  '/dashboard/accountsetting/role/$roleId': typeof DashboardAccountsettingRoleRoleIdRoute
  '/dashboard/accountsetting/role/create': typeof DashboardAccountsettingRoleCreateRoute
  '/dashboard/accountsetting/staff/create': typeof DashboardAccountsettingStaffCreateRoute
  '/dashboard/manual-book/edit/$id': typeof DashboardManualBookEditIdRoute
  '/dashboard/accountsetting/attendance': typeof DashboardAccountsettingAttendanceIndexRoute
  '/dashboard/accountsetting/role': typeof DashboardAccountsettingRoleIndexRoute
  '/dashboard/accountsetting/staff': typeof DashboardAccountsettingStaffIndexRoute
  '/dashboard/accountsetting/withdrawal': typeof DashboardAccountsettingWithdrawalIndexRoute
  '/dashboard/setting/article': typeof DashboardSettingArticleIndexRoute
  '/dashboard/setting/landing': typeof DashboardSettingLandingIndexRoute
  '/dashboard/setting/tutorial': typeof DashboardSettingTutorialIndexRoute
  '/dashboard/wallet/bank-account': typeof DashboardWalletBankAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/billing': typeof BillingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/l/$code': typeof LCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/accountsetting/shift': typeof DashboardAccountsettingShiftRouteRoute
  '/dashboard/attendance/me': typeof DashboardAttendanceMeRouteRoute
  '/dashboard/account/$slug': typeof DashboardAccountSlugRoute
  '/dashboard/account/create': typeof DashboardAccountCreateRoute
  '/dashboard/accountsetting/devices': typeof DashboardAccountsettingDevicesRoute
  '/dashboard/email/$id': typeof DashboardEmailIdRoute
  '/dashboard/email/create': typeof DashboardEmailCreateRoute
  '/dashboard/manual-book/$slug': typeof DashboardManualBookSlugRoute
  '/dashboard/manual-book/write': typeof DashboardManualBookWriteRoute
  '/dashboard/platform-product/$id': typeof DashboardPlatformProductIdRoute
  '/dashboard/platform-product/create': typeof DashboardPlatformProductCreateRoute
  '/dashboard/product/create': typeof DashboardProductCreateRoute
  '/dashboard/transaction/create': typeof DashboardTransactionCreateRoute
  '/dashboard/account/': typeof DashboardAccountIndexRoute
  '/dashboard/accountsetting/': typeof DashboardAccountsettingIndexRoute
  '/dashboard/email-message/': typeof DashboardEmailMessageIndexRoute
  '/dashboard/email/': typeof DashboardEmailIndexRoute
  '/dashboard/manual-book/': typeof DashboardManualBookIndexRoute
  '/dashboard/platform-product/': typeof DashboardPlatformProductIndexRoute
  '/dashboard/product/': typeof DashboardProductIndexRoute
  '/dashboard/setting/': typeof DashboardSettingIndexRoute
  '/dashboard/transaction/': typeof DashboardTransactionIndexRoute
  '/dashboard/voucher-generator/': typeof DashboardVoucherGeneratorIndexRoute
  '/dashboard/wallet/': typeof DashboardWalletIndexRoute
  '/dashboard/accountsetting/attendance/report': typeof DashboardAccountsettingAttendanceReportRouteRoute
  '/dashboard/accountsetting/role/$roleId': typeof DashboardAccountsettingRoleRoleIdRoute
  '/dashboard/accountsetting/role/create': typeof DashboardAccountsettingRoleCreateRoute
  '/dashboard/accountsetting/staff/create': typeof DashboardAccountsettingStaffCreateRoute
  '/dashboard/manual-book/edit/$id': typeof DashboardManualBookEditIdRoute
  '/dashboard/accountsetting/attendance/': typeof DashboardAccountsettingAttendanceIndexRoute
  '/dashboard/accountsetting/role/': typeof DashboardAccountsettingRoleIndexRoute
  '/dashboard/accountsetting/staff/': typeof DashboardAccountsettingStaffIndexRoute
  '/dashboard/accountsetting/withdrawal/': typeof DashboardAccountsettingWithdrawalIndexRoute
  '/dashboard/setting/article/': typeof DashboardSettingArticleIndexRoute
  '/dashboard/setting/landing/': typeof DashboardSettingLandingIndexRoute
  '/dashboard/setting/tutorial/': typeof DashboardSettingTutorialIndexRoute
  '/dashboard/wallet/bank-account/': typeof DashboardWalletBankAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/billing'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/l/$code'
    | '/dashboard/'
    | '/dashboard/accountsetting/shift'
    | '/dashboard/attendance/me'
    | '/dashboard/account/$slug'
    | '/dashboard/account/create'
    | '/dashboard/accountsetting/devices'
    | '/dashboard/email/$id'
    | '/dashboard/email/create'
    | '/dashboard/manual-book/$slug'
    | '/dashboard/manual-book/write'
    | '/dashboard/platform-product/$id'
    | '/dashboard/platform-product/create'
    | '/dashboard/product/create'
    | '/dashboard/transaction/create'
    | '/dashboard/account'
    | '/dashboard/accountsetting'
    | '/dashboard/email-message'
    | '/dashboard/email'
    | '/dashboard/manual-book'
    | '/dashboard/platform-product'
    | '/dashboard/product'
    | '/dashboard/setting'
    | '/dashboard/transaction'
    | '/dashboard/voucher-generator'
    | '/dashboard/wallet'
    | '/dashboard/accountsetting/attendance/report'
    | '/dashboard/accountsetting/role/$roleId'
    | '/dashboard/accountsetting/role/create'
    | '/dashboard/accountsetting/staff/create'
    | '/dashboard/manual-book/edit/$id'
    | '/dashboard/accountsetting/attendance'
    | '/dashboard/accountsetting/role'
    | '/dashboard/accountsetting/staff'
    | '/dashboard/accountsetting/withdrawal'
    | '/dashboard/setting/article'
    | '/dashboard/setting/landing'
    | '/dashboard/setting/tutorial'
    | '/dashboard/wallet/bank-account'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/l/$code'
    | '/dashboard'
    | '/dashboard/accountsetting/shift'
    | '/dashboard/attendance/me'
    | '/dashboard/account/$slug'
    | '/dashboard/account/create'
    | '/dashboard/accountsetting/devices'
    | '/dashboard/email/$id'
    | '/dashboard/email/create'
    | '/dashboard/manual-book/$slug'
    | '/dashboard/manual-book/write'
    | '/dashboard/platform-product/$id'
    | '/dashboard/platform-product/create'
    | '/dashboard/product/create'
    | '/dashboard/transaction/create'
    | '/dashboard/account'
    | '/dashboard/accountsetting'
    | '/dashboard/email-message'
    | '/dashboard/email'
    | '/dashboard/manual-book'
    | '/dashboard/platform-product'
    | '/dashboard/product'
    | '/dashboard/setting'
    | '/dashboard/transaction'
    | '/dashboard/voucher-generator'
    | '/dashboard/wallet'
    | '/dashboard/accountsetting/attendance/report'
    | '/dashboard/accountsetting/role/$roleId'
    | '/dashboard/accountsetting/role/create'
    | '/dashboard/accountsetting/staff/create'
    | '/dashboard/manual-book/edit/$id'
    | '/dashboard/accountsetting/attendance'
    | '/dashboard/accountsetting/role'
    | '/dashboard/accountsetting/staff'
    | '/dashboard/accountsetting/withdrawal'
    | '/dashboard/setting/article'
    | '/dashboard/setting/landing'
    | '/dashboard/setting/tutorial'
    | '/dashboard/wallet/bank-account'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/billing'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/l/$code'
    | '/dashboard/'
    | '/dashboard/accountsetting/shift'
    | '/dashboard/attendance/me'
    | '/dashboard/account/$slug'
    | '/dashboard/account/create'
    | '/dashboard/accountsetting/devices'
    | '/dashboard/email/$id'
    | '/dashboard/email/create'
    | '/dashboard/manual-book/$slug'
    | '/dashboard/manual-book/write'
    | '/dashboard/platform-product/$id'
    | '/dashboard/platform-product/create'
    | '/dashboard/product/create'
    | '/dashboard/transaction/create'
    | '/dashboard/account/'
    | '/dashboard/accountsetting/'
    | '/dashboard/email-message/'
    | '/dashboard/email/'
    | '/dashboard/manual-book/'
    | '/dashboard/platform-product/'
    | '/dashboard/product/'
    | '/dashboard/setting/'
    | '/dashboard/transaction/'
    | '/dashboard/voucher-generator/'
    | '/dashboard/wallet/'
    | '/dashboard/accountsetting/attendance/report'
    | '/dashboard/accountsetting/role/$roleId'
    | '/dashboard/accountsetting/role/create'
    | '/dashboard/accountsetting/staff/create'
    | '/dashboard/manual-book/edit/$id'
    | '/dashboard/accountsetting/attendance/'
    | '/dashboard/accountsetting/role/'
    | '/dashboard/accountsetting/staff/'
    | '/dashboard/accountsetting/withdrawal/'
    | '/dashboard/setting/article/'
    | '/dashboard/setting/landing/'
    | '/dashboard/setting/tutorial/'
    | '/dashboard/wallet/bank-account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  BillingRoute: typeof BillingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LCodeRoute: typeof LCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/l/$code': {
      id: '/l/$code'
      path: '/l/$code'
      fullPath: '/l/$code'
      preLoaderRoute: typeof LCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet/': {
      id: '/dashboard/wallet/'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/voucher-generator/': {
      id: '/dashboard/voucher-generator/'
      path: '/voucher-generator'
      fullPath: '/dashboard/voucher-generator'
      preLoaderRoute: typeof DashboardVoucherGeneratorIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transaction/': {
      id: '/dashboard/transaction/'
      path: '/transaction'
      fullPath: '/dashboard/transaction'
      preLoaderRoute: typeof DashboardTransactionIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/setting/': {
      id: '/dashboard/setting/'
      path: '/setting'
      fullPath: '/dashboard/setting'
      preLoaderRoute: typeof DashboardSettingIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product/': {
      id: '/dashboard/product/'
      path: '/product'
      fullPath: '/dashboard/product'
      preLoaderRoute: typeof DashboardProductIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/platform-product/': {
      id: '/dashboard/platform-product/'
      path: '/platform-product'
      fullPath: '/dashboard/platform-product'
      preLoaderRoute: typeof DashboardPlatformProductIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/manual-book/': {
      id: '/dashboard/manual-book/'
      path: '/manual-book'
      fullPath: '/dashboard/manual-book'
      preLoaderRoute: typeof DashboardManualBookIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email/': {
      id: '/dashboard/email/'
      path: '/email'
      fullPath: '/dashboard/email'
      preLoaderRoute: typeof DashboardEmailIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email-message/': {
      id: '/dashboard/email-message/'
      path: '/email-message'
      fullPath: '/dashboard/email-message'
      preLoaderRoute: typeof DashboardEmailMessageIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountsetting/': {
      id: '/dashboard/accountsetting/'
      path: '/accountsetting'
      fullPath: '/dashboard/accountsetting'
      preLoaderRoute: typeof DashboardAccountsettingIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account/': {
      id: '/dashboard/account/'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transaction/create': {
      id: '/dashboard/transaction/create'
      path: '/transaction/create'
      fullPath: '/dashboard/transaction/create'
      preLoaderRoute: typeof DashboardTransactionCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product/create': {
      id: '/dashboard/product/create'
      path: '/product/create'
      fullPath: '/dashboard/product/create'
      preLoaderRoute: typeof DashboardProductCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/platform-product/create': {
      id: '/dashboard/platform-product/create'
      path: '/platform-product/create'
      fullPath: '/dashboard/platform-product/create'
      preLoaderRoute: typeof DashboardPlatformProductCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/platform-product/$id': {
      id: '/dashboard/platform-product/$id'
      path: '/platform-product/$id'
      fullPath: '/dashboard/platform-product/$id'
      preLoaderRoute: typeof DashboardPlatformProductIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/manual-book/write': {
      id: '/dashboard/manual-book/write'
      path: '/manual-book/write'
      fullPath: '/dashboard/manual-book/write'
      preLoaderRoute: typeof DashboardManualBookWriteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/manual-book/$slug': {
      id: '/dashboard/manual-book/$slug'
      path: '/manual-book/$slug'
      fullPath: '/dashboard/manual-book/$slug'
      preLoaderRoute: typeof DashboardManualBookSlugRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email/create': {
      id: '/dashboard/email/create'
      path: '/email/create'
      fullPath: '/dashboard/email/create'
      preLoaderRoute: typeof DashboardEmailCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email/$id': {
      id: '/dashboard/email/$id'
      path: '/email/$id'
      fullPath: '/dashboard/email/$id'
      preLoaderRoute: typeof DashboardEmailIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountsetting/devices': {
      id: '/dashboard/accountsetting/devices'
      path: '/accountsetting/devices'
      fullPath: '/dashboard/accountsetting/devices'
      preLoaderRoute: typeof DashboardAccountsettingDevicesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account/create': {
      id: '/dashboard/account/create'
      path: '/account/create'
      fullPath: '/dashboard/account/create'
      preLoaderRoute: typeof DashboardAccountCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account/$slug': {
      id: '/dashboard/account/$slug'
      path: '/account/$slug'
      fullPath: '/dashboard/account/$slug'
      preLoaderRoute: typeof DashboardAccountSlugRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/attendance/me': {
      id: '/dashboard/attendance/me'
      path: '/attendance/me'
      fullPath: '/dashboard/attendance/me'
      preLoaderRoute: typeof DashboardAttendanceMeRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountsetting/shift': {
      id: '/dashboard/accountsetting/shift'
      path: '/accountsetting/shift'
      fullPath: '/dashboard/accountsetting/shift'
      preLoaderRoute: typeof DashboardAccountsettingShiftRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/wallet/bank-account/': {
      id: '/dashboard/wallet/bank-account/'
      path: '/wallet/bank-account'
      fullPath: '/dashboard/wallet/bank-account'
      preLoaderRoute: typeof DashboardWalletBankAccountIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/setting/tutorial/': {
      id: '/dashboard/setting/tutorial/'
      path: '/setting/tutorial'
      fullPath: '/dashboard/setting/tutorial'
      preLoaderRoute: typeof DashboardSettingTutorialIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/setting/landing/': {
      id: '/dashboard/setting/landing/'
      path: '/setting/landing'
      fullPath: '/dashboard/setting/landing'
      preLoaderRoute: typeof DashboardSettingLandingIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/setting/article/': {
      id: '/dashboard/setting/article/'
      path: '/setting/article'
      fullPath: '/dashboard/setting/article'
      preLoaderRoute: typeof DashboardSettingArticleIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountsetting/withdrawal/': {
      id: '/dashboard/accountsetting/withdrawal/'
      path: '/accountsetting/withdrawal'
      fullPath: '/dashboard/accountsetting/withdrawal'
      preLoaderRoute: typeof DashboardAccountsettingWithdrawalIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountsetting/staff/': {
      id: '/dashboard/accountsetting/staff/'
      path: '/accountsetting/staff'
      fullPath: '/dashboard/accountsetting/staff'
      preLoaderRoute: typeof DashboardAccountsettingStaffIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountsetting/role/': {
      id: '/dashboard/accountsetting/role/'
      path: '/accountsetting/role'
      fullPath: '/dashboard/accountsetting/role'
      preLoaderRoute: typeof DashboardAccountsettingRoleIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountsetting/attendance/': {
      id: '/dashboard/accountsetting/attendance/'
      path: '/accountsetting/attendance'
      fullPath: '/dashboard/accountsetting/attendance'
      preLoaderRoute: typeof DashboardAccountsettingAttendanceIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/manual-book/edit/$id': {
      id: '/dashboard/manual-book/edit/$id'
      path: '/manual-book/edit/$id'
      fullPath: '/dashboard/manual-book/edit/$id'
      preLoaderRoute: typeof DashboardManualBookEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountsetting/staff/create': {
      id: '/dashboard/accountsetting/staff/create'
      path: '/accountsetting/staff/create'
      fullPath: '/dashboard/accountsetting/staff/create'
      preLoaderRoute: typeof DashboardAccountsettingStaffCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountsetting/role/create': {
      id: '/dashboard/accountsetting/role/create'
      path: '/accountsetting/role/create'
      fullPath: '/dashboard/accountsetting/role/create'
      preLoaderRoute: typeof DashboardAccountsettingRoleCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountsetting/role/$roleId': {
      id: '/dashboard/accountsetting/role/$roleId'
      path: '/accountsetting/role/$roleId'
      fullPath: '/dashboard/accountsetting/role/$roleId'
      preLoaderRoute: typeof DashboardAccountsettingRoleRoleIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountsetting/attendance/report': {
      id: '/dashboard/accountsetting/attendance/report'
      path: '/accountsetting/attendance/report'
      fullPath: '/dashboard/accountsetting/attendance/report'
      preLoaderRoute: typeof DashboardAccountsettingAttendanceReportRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountsettingShiftRouteRoute: typeof DashboardAccountsettingShiftRouteRoute
  DashboardAttendanceMeRouteRoute: typeof DashboardAttendanceMeRouteRoute
  DashboardAccountSlugRoute: typeof DashboardAccountSlugRoute
  DashboardAccountCreateRoute: typeof DashboardAccountCreateRoute
  DashboardAccountsettingDevicesRoute: typeof DashboardAccountsettingDevicesRoute
  DashboardEmailIdRoute: typeof DashboardEmailIdRoute
  DashboardEmailCreateRoute: typeof DashboardEmailCreateRoute
  DashboardManualBookSlugRoute: typeof DashboardManualBookSlugRoute
  DashboardManualBookWriteRoute: typeof DashboardManualBookWriteRoute
  DashboardPlatformProductIdRoute: typeof DashboardPlatformProductIdRoute
  DashboardPlatformProductCreateRoute: typeof DashboardPlatformProductCreateRoute
  DashboardProductCreateRoute: typeof DashboardProductCreateRoute
  DashboardTransactionCreateRoute: typeof DashboardTransactionCreateRoute
  DashboardAccountIndexRoute: typeof DashboardAccountIndexRoute
  DashboardAccountsettingIndexRoute: typeof DashboardAccountsettingIndexRoute
  DashboardEmailMessageIndexRoute: typeof DashboardEmailMessageIndexRoute
  DashboardEmailIndexRoute: typeof DashboardEmailIndexRoute
  DashboardManualBookIndexRoute: typeof DashboardManualBookIndexRoute
  DashboardPlatformProductIndexRoute: typeof DashboardPlatformProductIndexRoute
  DashboardProductIndexRoute: typeof DashboardProductIndexRoute
  DashboardSettingIndexRoute: typeof DashboardSettingIndexRoute
  DashboardTransactionIndexRoute: typeof DashboardTransactionIndexRoute
  DashboardVoucherGeneratorIndexRoute: typeof DashboardVoucherGeneratorIndexRoute
  DashboardWalletIndexRoute: typeof DashboardWalletIndexRoute
  DashboardAccountsettingAttendanceReportRouteRoute: typeof DashboardAccountsettingAttendanceReportRouteRoute
  DashboardAccountsettingRoleRoleIdRoute: typeof DashboardAccountsettingRoleRoleIdRoute
  DashboardAccountsettingRoleCreateRoute: typeof DashboardAccountsettingRoleCreateRoute
  DashboardAccountsettingStaffCreateRoute: typeof DashboardAccountsettingStaffCreateRoute
  DashboardManualBookEditIdRoute: typeof DashboardManualBookEditIdRoute
  DashboardAccountsettingAttendanceIndexRoute: typeof DashboardAccountsettingAttendanceIndexRoute
  DashboardAccountsettingRoleIndexRoute: typeof DashboardAccountsettingRoleIndexRoute
  DashboardAccountsettingStaffIndexRoute: typeof DashboardAccountsettingStaffIndexRoute
  DashboardAccountsettingWithdrawalIndexRoute: typeof DashboardAccountsettingWithdrawalIndexRoute
  DashboardSettingArticleIndexRoute: typeof DashboardSettingArticleIndexRoute
  DashboardSettingLandingIndexRoute: typeof DashboardSettingLandingIndexRoute
  DashboardSettingTutorialIndexRoute: typeof DashboardSettingTutorialIndexRoute
  DashboardWalletBankAccountIndexRoute: typeof DashboardWalletBankAccountIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountsettingShiftRouteRoute:
    DashboardAccountsettingShiftRouteRoute,
  DashboardAttendanceMeRouteRoute: DashboardAttendanceMeRouteRoute,
  DashboardAccountSlugRoute: DashboardAccountSlugRoute,
  DashboardAccountCreateRoute: DashboardAccountCreateRoute,
  DashboardAccountsettingDevicesRoute: DashboardAccountsettingDevicesRoute,
  DashboardEmailIdRoute: DashboardEmailIdRoute,
  DashboardEmailCreateRoute: DashboardEmailCreateRoute,
  DashboardManualBookSlugRoute: DashboardManualBookSlugRoute,
  DashboardManualBookWriteRoute: DashboardManualBookWriteRoute,
  DashboardPlatformProductIdRoute: DashboardPlatformProductIdRoute,
  DashboardPlatformProductCreateRoute: DashboardPlatformProductCreateRoute,
  DashboardProductCreateRoute: DashboardProductCreateRoute,
  DashboardTransactionCreateRoute: DashboardTransactionCreateRoute,
  DashboardAccountIndexRoute: DashboardAccountIndexRoute,
  DashboardAccountsettingIndexRoute: DashboardAccountsettingIndexRoute,
  DashboardEmailMessageIndexRoute: DashboardEmailMessageIndexRoute,
  DashboardEmailIndexRoute: DashboardEmailIndexRoute,
  DashboardManualBookIndexRoute: DashboardManualBookIndexRoute,
  DashboardPlatformProductIndexRoute: DashboardPlatformProductIndexRoute,
  DashboardProductIndexRoute: DashboardProductIndexRoute,
  DashboardSettingIndexRoute: DashboardSettingIndexRoute,
  DashboardTransactionIndexRoute: DashboardTransactionIndexRoute,
  DashboardVoucherGeneratorIndexRoute: DashboardVoucherGeneratorIndexRoute,
  DashboardWalletIndexRoute: DashboardWalletIndexRoute,
  DashboardAccountsettingAttendanceReportRouteRoute:
    DashboardAccountsettingAttendanceReportRouteRoute,
  DashboardAccountsettingRoleRoleIdRoute:
    DashboardAccountsettingRoleRoleIdRoute,
  DashboardAccountsettingRoleCreateRoute:
    DashboardAccountsettingRoleCreateRoute,
  DashboardAccountsettingStaffCreateRoute:
    DashboardAccountsettingStaffCreateRoute,
  DashboardManualBookEditIdRoute: DashboardManualBookEditIdRoute,
  DashboardAccountsettingAttendanceIndexRoute:
    DashboardAccountsettingAttendanceIndexRoute,
  DashboardAccountsettingRoleIndexRoute: DashboardAccountsettingRoleIndexRoute,
  DashboardAccountsettingStaffIndexRoute:
    DashboardAccountsettingStaffIndexRoute,
  DashboardAccountsettingWithdrawalIndexRoute:
    DashboardAccountsettingWithdrawalIndexRoute,
  DashboardSettingArticleIndexRoute: DashboardSettingArticleIndexRoute,
  DashboardSettingLandingIndexRoute: DashboardSettingLandingIndexRoute,
  DashboardSettingTutorialIndexRoute: DashboardSettingTutorialIndexRoute,
  DashboardWalletBankAccountIndexRoute: DashboardWalletBankAccountIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  BillingRoute: BillingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LCodeRoute: LCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
