export const NETFLIX_RESET_PASSWORD = 'NETFLIX_RESET_PASSWORD';
export const NETFLIX_AUTO_RELOAD = 'NETFLIX_AUTO_RELOAD';
export const NETFLIX_AUTO_UPGRADE = 'NETFLIX_AUTO_UPGRADE';
export const NETFLIX_LOGIN_TV = 'NETFLIX_LOGIN_TV';
export const NETFLIX_GET_TOKEN = 'NETFLIX_GET_TOKEN';
export const SUBS_END_NOTIFY = 'SUBS_END_NOTIFY';
export const UNFREEZE_ACCOUNT = 'UNFREEZE_ACCOUNT';
export const SEND_WA_MESSAGE = 'SEND_WA_MESSAGE';
